In [1]:

from markov import MarkovChain,MarkovChainState,MarkovChainEdge
import numpy as np


In [2]:

def make_random_walk(num_states,p=.5):
    rows = [0,num_states-1]
    cols = [0,num_states-1]
    vals = [1,1]
    for i in range(1,num_states-1):
        rows += [i,i]
        cols += [i-1,i+1]
        vals += [1-p,p]
    return rows,cols,vals
    



In [3]:
rows,cols,vals = make_random_walk(num_states=25,p=.5)

RW = MarkovChain()
RW.from_rcv(rows,cols,vals)


In [4]:

print(RW.transition_matrix_is_valid)
RW.get_communication_classes()

print()
print(f'class type          states')
for cls,tp in zip(RW.classes,RW.types):
    print(f'{tp:20}{cls}')


True

class type          states
Transient           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Absorbing           [0]
Absorbing           [24]


In [5]:
RW.get_stationary_vector()
RW.stationary_vector

array([0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5])

In [6]:
A = np.array([[.2, .8, 0, 0,0,0,0,0,0,0],
              [.5, .5, 0, 0,0,0,0,0,0,0],
              [.25,.25,0,.5,0,0,0,0,0,0],
              [0,0,.5,0,0,.5,0,0,0,0],
              [0,0,0,0,1,0,0,0,0,0],
              [0,0,0,0,0,.5,.3,.2,0,0],
              [0,0,0,0,.25,.25,0,0,0,.5],
              [0,0,0,0,0,0,0,.1,.8,.1],
              [0,0,0,0,0,0,0,.4,.2,.4],
              [0,0,0,0,0,0,0,.4,.4,.2]])
MC = MarkovChain()
MC.from_nparray(A)
MC.get_transition_matrix(format='np')

array([[0.2 , 0.8 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.5 , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.5 , 0.  , 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.3 , 0.2 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.25, 0.25, 0.  , 0.  , 0.  , 0.5 ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.8 , 0.1 ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.4 , 0.2 , 0.4 ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.4 , 0.4 , 0.2 ]])

In [7]:
MC.get_transition_matrix()

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [8]:

# RW.analyze()

MC.get_transition_matrix_decomposition()
MC.get_canonical_transition_matrix()
MC.get_expected_visits_matrix()
MC.get_absorption_probability_matrix()
MC.get_expected_time_to_absorption_matrix()

print()
print('Expected number of times to visit state j starting from state i:')
print(MC.N.todense()) # Expected number of times to visit state j starting from state i

print()
print('Probability of being absorbed into state j starting from state i:')
print(MC.B.todense()) # Probability of being absorbed into state j starting from state i

print()
print('Expected time to absorption, starting from state i:')
print(MC.T.todense()) # Expected time to absorption, starting from state i

x = MC.simulate(n=200,initial=8) # Simulate the Markov chain for 200 time steps
                                 # with initial state 8.


Expected number of times to visit state j starting from state i:
[[2.35294118 0.70588235 0.         0.        ]
 [0.58823529 1.17647059 0.         0.        ]
 [0.         0.         1.33333333 0.66666667]
 [0.         0.         0.66666667 1.33333333]]

Probability of being absorbed into state j starting from state i:
[[0.         0.         0.47058824 0.         0.35294118 0.17647059]
 [0.         0.         0.11764706 0.         0.58823529 0.29411765]
 [0.33333333 0.33333333 0.         0.         0.         0.        ]
 [0.16666667 0.16666667 0.         0.         0.         0.        ]]

Expected time to absorption, starting from state i:
[[3.05882353]
 [1.76470588]
 [2.        ]
 [2.        ]]


In [9]:
MC.canonical_transition_matrix.todense()

matrix([[0.5 , 0.3 , 0.  , 0.  , 0.  , 0.  , 0.2 , 0.  , 0.  , 0.  ],
        [0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.5 , 0.25],
        [0.  , 0.  , 0.  , 0.5 , 0.25, 0.25, 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.2 , 0.8 , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.5 , 0.5 , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.8 , 0.1 , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.4 , 0.2 , 0.4 , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.4 , 0.4 , 0.2 , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  ]])

In [10]:

print(MC.transition_matrix_is_valid)
MC.get_communication_classes()

print()
print(f'class type          states')
for cls,tp in zip(MC.classes,MC.types):
    print(f'{tp:20}{cls}')

True

class type          states
Transient           [5, 6]
Transient           [2, 3]
Absorbing           [0, 1]
Absorbing           [7, 8, 9]
Absorbing           [4]


In [11]:
MC.is_ergodic

False

In [12]:
# MC.get_transition_matrix(format='np')
# MC.transition_matrix_is_valid

MC.get_stationary_vector()
MC.stationary_vector

array([0.12820513, 0.20512821, 0.        , 0.        , 0.33333333,
       0.        , 0.        , 0.1025641 , 0.14529915, 0.08547009])